# Generated by Django 5.2.4 on 2025-08-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_remove_enquiry_image'),
        ('users', '0004_shops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shops'),
        ),
    ]
