# Generated by Django 5.2.4 on 2025-07-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='image',
        ),
    ]
