# Generated by Django 5.2.4 on 2025-07-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Normal User'), ('OWNER', 'Shop Owner')], default='USER', max_length=10),
        ),
    ]
